""" This file is migration file. """

# Generated by Django 4.1.7 on 2023-03-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    This class is migration class for teacher_directory_app.
    """

    replaces = [('teacher_directory_app', '0001_initial'),
                ('teacher_directory_app', '0002_alter_teacher_room_number_and_more'),
                ('teacher_directory_app', '0003_alter_teacher_subject_taught'),
                ('teacher_directory_app', '0004_alter_teacher_subject_taught'),
                ('teacher_directory_app', '0005_alter_teacher_phone_number')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False,
                                           verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False,
                                           verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('profile_image', models.ImageField(default='profile_images/default_image.jpg',
                                                    upload_to='profile_images/')),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('room_number', models.CharField(max_length=10)),
                ('subject_taught', models.ManyToManyField(to='teacher_directory_app.subject')),
            ],
        ),
    ]
